# file: kvm_openstack_vi.yml
#
# play_name: kvm openstack virtualization infrastructure
# desc: Setup VLANs and Bridges for kvm networks. Aiming at 3 nodes Openstack 
#   deployment.
# modules:
#   - nmcli

---
- hosts: vi_nodes 
  vars:
    http_port: 80
    max_clients: 200
  roles:
    - common
    - kvm_host
    - role: kvm_network_vlan
      vlan_id: 1
      netmask: 192.168.100.0/24

  tasks:
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
      # listen: restart_apache # not working
      become: true

