# play_name: kvm_host_start.yml
# desc: Setup VLANs and Bridges for kvm networks.
# modules:
#   - nmcli

---
- hosts: localhost
  tasks:
  - name: ensure apache is running
    service: 
      name: httpd
      state: started
  - name: disable selinux
    command: /sbin/setenforce 0
    ignore_errors: True
    #notify: "restart web services"
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
      listen: "restart web services"

