# file: kvm_openstack_vi.yml
#
# play_name: kvm openstack virtualization infrastructure
# desc: Setup VLANs and Bridges for kvm networks. Aiming at 3 nodes Openstack 
#   deployment.
# modules:
#   - nmcli

---
- hosts: vi_nodes 
  vars:
    http_port: 80
    max_clients: 200
  roles:
    - common
    - kvm.host
  tasks:
    - name: ensure apache is running
      service: 
        name=httpd
        state=started
      become: true

    - name: disable selinux
      command: /sbin/setenforce 0
      ignore_errors: True
      become: true
      notify: 
        - "restart apache"

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
      # listen: restart_apache # not working
      become: true

